export default [
  'Scegli un ragazzo che beve',
  'Bevono i programmatori (e affini)',
  'Fai una battuta, un verso o simili. Beve chi ride',
  'Bevono tutti tranne te! Sfigato',
  'Lancia un dado. Se esce 1 bevi 3 sorsi. Se esce 6 scegli 6 persone che bevono. Altrimenti nulla',
  'Bevono i giovanotti - under 26 (compresi)',
  'Bevono i vecchietti - over 27 (compresi)',
  "Beve l'ultimo andato in bagno",
  'Beve chi ha una sorella',
  'Beve chi ha un fratello',
  'Fai un complimento a Simone, se ride beve lui',
  'Beve il più piccolo',
  'Beve il più vecchio',
  'Scegli un best friend. Per i prossimi 10 giri bevete sempre insieme, in ogni caso',
  'Beve chi è nato sotto il Po',
  'Beve chi è nato sopra il Po',
  'Bevono i giargiana',
  'Bevono i GYMBRO',
  'Beve quello alla tua DX',
  'Beve quello alla tua SX',
  'Scegli a chi regalare un sorso',
  'Bevono quelli in piedi',
  'Bevono quelli sul divano',
  'Bevono quelli sulla sedia',
  'Bevono i single',
  'Bevono i fidanzati',
  'Brinda con qualcuno',
  'Bevi un sorso del drink alla tua destra',
  'Bevi un sorso del drink alla tua sinistra',
  'Shotta il bicchiere',
  "Aggiungi un po' di Vodka nel tuo bicchiere",
  "Aggiungi un po' di Gin nel tuo bicchiere",
  'Bevono tutti',
  'Bevono i ragazzi',
  'Bevono le ragazze',
  'Bevono i/le biondi/e',
  'Bevono i/le castani/e',
  'Bevono i pelati/rasati',
  'Che sfiga! Non beve nessuno',
  'Condividi uno shottino con qualcuno',
  'Bevono i Sagittario',
  'Bevono i Capricorno',
  'Bevono i Cancro',
  'Bevono i Pesci',
  'Bevono i Gemelli',
  'Bevono gli Arieti',
  'Bevono i Tori',
  'Bevono i Leoni',
  'Bevono gli Scorpioni',
  'Bevono gli Acquario',
  'Bevono le Vergini',
  'Bevono le Bilance',
  'Scegli chi beve x2',
  'Scegli una ragazza che beve',
  'Bevi un sorso se ti sei cagato a dosso (over 5 anni)',
  'Bevi un sorso se ti sei segato/masturbato questa settimana',
  'Bevi un sorso se hai mai baciato Nad',
  'Bevi se hai mai mandato un messaggio vocale di oltre 5 minuti a qualcuno',
  'Bevi se hai mai cantato a squarciagola sotto la doccia fingendo di essere una rockstar',
  'Bevi se hai mai mandato un messaggio imbarazzante al tuo ex dopo la mezzanotte',
  "Bevi con chi hai mai condiviso segreti 'troppo imbarazzanti' per essere rivelati",
  "Bevi con chi hai mai dormito in un posto 'alternativo' (tipo una vasca da bagno o sul pavimento di un amico/a)",
  'Bevi se hai mai chiamato il tuo attuale partner con il nome del tuo ex',
  'Bevi se hai mai cercato il tuo nome su Google per vedere cosa esce',
  'Bevi se hai mai fatto finta di essere impegnato/a per evitare un tipo/a',
  'Bevi se ti è piaciuto MEGALOPOLIS',
  'Bevi se hai mai finto un orgasmo per far finire prima la cosa',
  "Bevi se hai mai inviato un messaggio 'hot' alla persona sbagliata",
  'Bevi se hai mai fatto sesso in un luogo pubblico (anche il parcheggio conta)',
  "Bevi se hai mai usato una scusa tipo 'ho mal di testa' per evitare il sesso",
  'Bevi se hai mai rotto una sedia o qualcosa su cui eri seduto/a',
  'Bevi se non hai mai scaricato Tinder',
  'Bevi se hai mai avuto coinquilini',
  'Bevi insieme alla tua dolce metà',
  'Bevi se hai una moto',
  "Bevi se hai un'auto",
  "Beve l'ultimo che tocca il pavimento",
  "Beve l'ultimo che tocca Simonello",
  "Beve l'ultimo che tocca Flavia",
  'Bevi se hai mai giocato a Magic',
  'Bevi se ricordi i nomi dei primi 151 Pokemon',
  'Mangia qualcosa daaaaai',
  'Bevi se segui Dario Moccia',
  'Bevi se hai mai masterato una campagna di DND',
  'Bevi insieme alla persona più simpatica',
  'Raccontaci qualcosa di te. Altrimenti shotta il bicchiere.',
  'Bevi se non sei mai salito in Tesla.',
  'Bevi se hai vomitato e dato la colpa a qualcun altro',
  'Bevi se hai i peli sul petto',
  'Bevi se hai un animale domestico (valgono anche le mucche)',
  'Mangia qualcosa insieme a Chiara, sceglie lei cosa',
  'Mangia qualcosa con Piotro, sceglie lui cosa',
  'Se sei un Vercesi tocca bere',
  'Bevi insieme alla persona che conosci meno, o non hai mai visto prima di oggi',
  'Fortunello/a… dicci solo il tuo colore preferito dai',
  "Scegli tu il 'Bevi se non hai'",
  "Beve l'ultimo che ha visto un film. Quale era il film?",
  "Beve l'ultimo che ha visto la puntata di un'anime. Che anime era?",
];
